"""Generate all Initial Tables

Revision ID: 9dfc2f77e49c
Revises: 
Create Date: 2023-12-09 00:33:32.788796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfc2f77e49c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_industry', sa.String(), nullable=False),
    sa.Column('business_link', sa.String(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('business_waitlist_users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('business_industry', sa.String(), nullable=False),
    sa.Column('business_link', sa.String(), nullable=True),
    sa.Column('subscribed', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('business_name'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subscribers',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('talent_users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('portfolio_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('talent_waitlist_users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_talent', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('is_business', sa.Boolean(), server_default='FALSE', nullable=True),
    sa.Column('subscribed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('talent_waitlist_users')
    op.drop_table('talent_users')
    op.drop_table('subscribers')
    op.drop_table('business_waitlist_users')
    op.drop_table('business_users')
    # ### end Alembic commands ###
